// Centralized route map for absolute production URLs
// Import this in components to avoid hardcoding paths

export const ROUTES = {
  home: 'https://essayembassy.com/',
  orderNow: 'https://essayembassy.com/order-now',
  login: 'https://essayembassy.com/login',
  privacy: 'https://essayembassy.com/privacy-policy',
  terms: 'https://essayembassy.com/terms-and-conditions',
  refund: 'https://essayembassy.com/refund-policy',
  contact: 'https://essayembassy.com/contact',
  writers: 'https://essayembassy.com/writers',
  samples: 'https://essayembassy.com/samples',
  reviews: 'https://essayembassy.com/reviews',
  qaLibrary: 'https://essayembassy.com/qa',
  register: 'https://essayembassy.com/register',

  // Services
  paperWritingServices: 'https://essayembassy.com/paper-writing-services',
  dissertationWritingServices: 'https://essayembassy.com/dissertation-writing-services',
  thesisWriting: 'https://essayembassy.com/thesis-writing',
  essayWriting: 'https://essayembassy.com/essay-writing',
  essayAdmission: 'https://essayembassy.com/admission',
  essayNarrative: 'https://essayembassy.com/narrative',
  essayArgumentative: 'https://essayembassy.com/argumentative',
  essayScholarship: 'https://essayembassy.com/scholarship',
  essayReflective: 'https://essayembassy.com/reflective',
  essayCompareContrast: 'https://essayembassy.com/compare-contrast',
  academicWriting: 'https://essayembassy.com/academic-writing',
  assignmentHelp: 'https://essayembassy.com/assignment-help/',
  assignManagement: 'https://essayembassy.com/assignment-help/management',
  assignComputer: 'https://essayembassy.com/assignment-help/computer',
  assignEngineering: 'https://essayembassy.com/assignment-help/engineering',
  assignScience: 'https://essayembassy.com/assignment-help/science',
  assignMath: 'https://essayembassy.com/assignment-help/math',
  assignLaw: 'https://essayembassy.com/assignment-help/law',
  assignEnglish: 'https://essayembassy.com/assignment-help/english',
  assignPhysics: 'https://essayembassy.com/assignment-help/physics',
  assignAccounting: 'https://essayembassy.com/assignment-help/accounting',
  assignChemistry: 'https://essayembassy.com/assignment-help/chemistry',
  homeworkHelp: 'https://essayembassy.com/homework-help/',
  homeworkHelpMath: 'https://essayembassy.com/homework-help/math',
  homeworkHelpManagement: 'https://essayembassy.com/homework-help/management',
  homeworkHelpProgramming: 'https://essayembassy.com/homework-help/programming',
  homeworkHelpScience: 'https://essayembassy.com/homework-help/science',
  homeworkHelpEngineering: 'https://essayembassy.com/homework-help/engineering',
  homeworkHelpMSOffice: 'https://essayembassy.com/homework-help/ms-office',
  homeworkHelpNursing: 'https://essayembassy.com/homework-help/nursing',
  homeworkHelpEconomics: 'https://essayembassy.com/homework-help/economics',
  homeworkHelpFinance: 'https://essayembassy.com/homework-help/finance',
  homeworkHelpAccounting: 'https://essayembassy.com/homework-help/accounting',
  homeworkHelpLaw: 'https://essayembassy.com/homework-help/law',
  homeworkHelpStatistics: 'https://essayembassy.com/homework-help/statistics',
  homeworkHelpHumanities: 'https://essayembassy.com/homework-help/humanities',

  programmingHelp: 'https://essayembassy.com/programming-help/',
  progPython: 'https://essayembassy.com/programming-help/python',
  progJava: 'https://essayembassy.com/programming-help/java',
  progJs: 'https://essayembassy.com/programming-help/js',
  progC: 'https://essayembassy.com/programming-help/c',
  progCsharp: 'https://essayembassy.com/programming-help/csharp',
  progCpp: 'https://essayembassy.com/programming-help/cpp',
  progMatlab: 'https://essayembassy.com/programming-help/matlab',
  progRuby: 'https://essayembassy.com/programming-help/ruby',
};

export type RouteKey = keyof typeof ROUTES;

