import React, { useEffect, useState } from 'react';

const EvolvingDocumentVisual: React.FC = () => {
  const documentLines = [
    "Title: The Role of Critical Thinking in Academic Success",
    "Abstract:",
    "  This paper investigates the foundational importance of critical thinking skills in fostering academic achievement across diverse disciplines. It explores how students who actively engage in analytical reasoning, evaluation of evidence, and logical argumentation consistently demonstrate superior performance in complex problem-solving and essay composition.",
    "",
    "Keywords: critical thinking, academic success, higher education, analytical skills, essay writing",
    "",
    "1. Introduction",
    "  In the contemporary educational landscape, the mere acquisition of facts is no longer sufficient. Universities increasingly emphasize the development of higher-order thinking skills, with critical thinking standing as a cornerstone of intellectual growth and academic proficiency. This introduction delineates the scope and objectives of the present study, positing that a robust engagement with critical thinking methodologies correlates directly with enhanced learning outcomes and scholarly output.",
    "",
    "2. Defining Critical Thinking",
    "  Critical thinking, as conceptualized within this discourse, transcends simplistic memorization, encompassing a nuanced ability to analyze, synthesize, and evaluate information objectively. It involves the disciplined process of actively and skillfully conceptualizing, applying, analyzing, synthesizing, and/or evaluating information gathered from, or generated by, observation, experience, reflection, reasoning, or communication, as a guide to belief and action."
  ];

  const [displayedText, setDisplayedText] = useState<string[]>([]);
  const [lineIndex, setLineIndex] = useState(0);
  const [charIndex, setCharIndex] = useState(0);
  const [isTypingComplete, setIsTypingComplete] = useState(false);

  useEffect(() => {
    if (lineIndex < documentLines.length) {
      if (charIndex < documentLines[lineIndex].length) {
        const timeout = setTimeout(() => {
          setDisplayedText(prev => {
            const newText = [...prev];
            if (newText[lineIndex] === undefined) {
              newText[lineIndex] = '';
            }
            newText[lineIndex] += documentLines[lineIndex][charIndex];
            return newText;
          });
          setCharIndex(charIndex + 1);
        }, 20); // Faster typing speed for document

        return () => clearTimeout(timeout);
      } else {
        // Move to the next line after a short pause
        const linePause = setTimeout(() => {
          setLineIndex(lineIndex + 1);
          setCharIndex(0);
          if (lineIndex + 1 < documentLines.length) {
            setDisplayedText(prev => [...prev, '']); // Add a new empty line for the next text
          }
        }, 400); // Pause before next line

        return () => clearTimeout(linePause);
      }
    } else {
      setIsTypingComplete(true);
      // Optional: Loop the animation after a delay
      setTimeout(() => {
        setDisplayedText([]);
        setLineIndex(0);
        setCharIndex(0);
        setIsTypingComplete(false);
      }, 8000); // Restart after 8 seconds
    }
  }, [lineIndex, charIndex, documentLines]);

  return (
    <div className="relative bg-gray-900 rounded-2xl shadow-xl overflow-hidden aspect-video max-w-full lg:max-w-none mx-auto lg:mx-0">
      {/* Top bar of the editor */}
      <div className="flex items-center p-3 bg-gray-800 border-b border-gray-700">
        <div className="flex space-x-2">
          <span className="w-3 h-3 rounded-full bg-red-500"></span>
          <span className="w-3 h-3 rounded-full bg-yellow-500"></span>
          <span className="w-3 h-3 rounded-full bg-green-500"></span>
        </div>
        <span className="flex-1 text-center text-gray-400 text-sm font-mono">MyEssay.docx</span>
      </div>

      {/* Document text area */}
      <div className="p-4 text-gray-300 text-sm font-mono leading-relaxed whitespace-pre-wrap h-[calc(100%-48px)] overflow-hidden"> {/* Adjusted height */}
        {displayedText.map((line, idx) => (
          <div key={idx} className="flex">
            <span className="text-gray-500 mr-3 select-none">{idx + 1}</span>
            <span>{line}</span>
          </div>
        ))}
        {/* Blinking cursor */}
        {!isTypingComplete && (lineIndex < documentLines.length) && (
          <span className="inline-block w-2 h-4 bg-green-400 animate-blink align-text-bottom"></span>
        )}
      </div>
    </div>
  );
};

export default EvolvingDocumentVisual;
